[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/admin"
  to = "/login"
  status = 302 